export const COLORS = {
  BACKGROUND: '#1B1A17',
  SURFACE: '#1F1E1B',
  PRIMARY: '#A35709',
  SECONDARY: '#FF8303',
  ACCENT: '#F0E3CA',
  TEXT_PRIMARY: '#FFFFFF',
  TEXT_SECONDARY: '#CCCCCC',
  BORDER: '#1F1E1B',
};