export const COLORS = {
  BACKGROUND: '#1B1A17',
  BACKGROUND_SECONDARY: '#242320',
  PRIMARY: '#FF8303',
  TEXT_PRIMARY: '#F0E3CA',
  TEXT_PRIMARY_LOW_OPACITY: '#F0E3CAA3',
  TEXT_SECONDARY: '#FFFFFF',
};